name: Repo Visualization

on:
  push:
    branches:
      - main

jobs:
  visualize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "diagram.svg"
          excluded_paths: "dist,node_modules"

      - name: Upload Diagram Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-diagram
          path: diagram.svg
